
pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: 'projects/openttd_vs141.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  dependenciesRevision: 'cf6e5ec1dc135153583cc42ac0c33bad4f8bceaa'

steps:
- script: |
    mkdir dep
    cd dep
    git clone https://github.com/nielsmh/OpenTTD-deps.git .
    git checkout $(dependenciesRevision)
    copy openttd_vs141.vcxproj.user ../projects/
- task: VSBuild@1

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

