
pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: 'projects/openttd_vs141.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  dependenciesRevision: 'cf6e5ec1dc135153583cc42ac0c33bad4f8bceaa'

steps:
- bash: |
    mkdir dep
    cd dep
    git clone https://github.com/nielsmh/OpenTTD-deps.git .
    git checkout $(dependenciesRevision)
- task: CopyFiles@2
  inputs:
    sourceFolder: 'dep'
    targetFolder: 'projects'
    contents: 'openttd_vs141.vcxproj.user'
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'bin'
    includeRootFolder: false
    archiveType: '7z'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).7z'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'win64-bin'
    targetPath: '$(Build.ArtifactStagingDirectory)'
